name: tp0-quiniela
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini:ro
      - ./server/data:/data
    networks:
      - testing_net

  agencia1:
    container_name: agencia1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=server:8080
      - CLI_LOOP_AMOUNT=1
      - CLI_LOOP_PERIOD=1s
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  agencia2:
    container_name: agencia2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_SERVER_ADDRESS=server:8080
      - CLI_LOOP_AMOUNT=1
      - CLI_LOOP_PERIOD=1s
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=María José
      - APELLIDO=González
      - DOCUMENTO=12345678
      - NACIMIENTO=1985-07-22
      - NUMERO=1234
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  agencia3:
    container_name: agencia3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_SERVER_ADDRESS=server:8080
      - CLI_LOOP_AMOUNT=1
      - CLI_LOOP_PERIOD=1s
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=Carlos Alberto
      - APELLIDO=Rodríguez
      - DOCUMENTO=87654321
      - NACIMIENTO=1992-11-15
      - NUMERO=5678
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  agencia4:
    container_name: agencia4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_SERVER_ADDRESS=server:8080
      - CLI_LOOP_AMOUNT=1
      - CLI_LOOP_PERIOD=1s
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=Ana Sofía
      - APELLIDO=López
      - DOCUMENTO=11223344
      - NACIMIENTO=1988-04-30
      - NUMERO=9999
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  agencia5:
    container_name: agencia5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_SERVER_ADDRESS=server:8080
      - CLI_LOOP_AMOUNT=1
      - CLI_LOOP_PERIOD=1s
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=Juan Pedro
      - APELLIDO=Martínez
      - DOCUMENTO=55667788
      - NACIMIENTO=1995-09-08
      - NUMERO=1111
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
